-- NOTE: This didn't decompile correctly. Work in progress.

function CfgCreditsData()
	0(1, 2, 3, 4, 
	CfgCredits("ROCKSTAR TORONTO", IDT_Nil);
	CfgCredits("Technical Director", "KEVIN HOARE");
	CfgCredits("Creative Director", "GREG BICK");
	CfgCredits("Producer", "ROB NELSON");
	CfgCredits("Lead Design", "JOHN MACPHERSON");
	CfgCredits("Lead Design", "SERGEI KUPREJANOV");
	CfgCredits("Design", "ALAN BLAINE");
	CfgCredits("Design", "ANDREW DUTHIE");
	CfgCredits("Design", "DAMIAN EBANKS");
	CfgCredits("Design", "JOSH NEEDLEMAN");
	CfgCredits("Design", "MATT WEST");
	CfgCredits("Programming", "FRANK KOZUH");
	CfgCredits("Programming", "GRANT KIM");
	CfgCredits("Programming", "JON PAUL SCHELTER");
	CfgCredits("Programming", "KASH SHAMIM");
	CfgCredits("Programming", "LEIGH MCRAE");
	CfgCredits("Programming", "MATTHEW PUTHIAMPADAVIL");
	CfgCredits("Programming", "NICK SNELL");
	CfgCredits("Programming", "OSCAR VALER");
	CfgCredits("Programming", "ROBERT MOBBS");
	CfgCredits("Programming", "STEPHEN ORR");
	CfgCredits("Lead Technical Artist", "ALAN BLAINE");
	CfgCredits("Gameplay Scripting", "ANDY KWIATKOWSKI");
	CfgCredits("Gameplay Scripting", "COLIN ORR");
	CfgCredits("Gameplay Scripting", "MATT WEST");
	CfgCredits("Gameplay Scripting", "MATTHEW SEVERIN");
	CfgCredits("Gameplay Scripting", "REGINALD WOODS");
	CfgCredits("Gameplay Scripting", "SCOTT PENMAN");
	CfgCredits("Gameplay Scripting", "TERRY LITRENTA");
	CfgCredits("Dialogue", "DAN VAN ZANT");
	CfgCredits("Dialogue", "MICHAEL THOMAS ZOCCANO");
	CfgCredits("Dialogue", "JOHN ZURHELLEN");
	CfgCredits("Sound and Music Design", "STEVE DONOHOE");
	CfgCredits("Graphic Design", "JONATHAN HODGE");
	CfgCredits("Lead Level Art", "CHRIS 'PENCILS' BABIC");
	CfgCredits("Lead Level Art", "PAUL MACPHERSON");
	CfgCredits("Level Art", "DANIEL EBANKS");
	CfgCredits("Level Art", "DENNY BORGES");
	CfgCredits("Level Art", "YUN KYUNG SUH");
	CfgCredits("Level Art", "LUKE SHELSWELL");
	CfgCredits("Level Art", "MIKE MARQUIS");
	CfgCredits("Level Art", "PETER MARSHALL");
	CfgCredits("Level Art", "PUM SARAI");
	CfgCredits("Lead Character Art", "KEVIN FREITAS");
	CfgCredits("Character Art", "BENJAMIN CHUE");
	CfgCredits("Character Art", "JONATHAN HODGE");
	CfgCredits("Character Art", "PETE ARMSTRONG");
	CfgCredits("Ingame Animation", "ABRAHAM AHMED");
	CfgCredits("Ingame Animation", "DAVID SAGUIL");
	CfgCredits("Ingame Animation", "JAMES HUMPHREYS");
	CfgCredits("Ingame Animation", "JOHN KIM");
	CfgCredits("Cutscene Animation", "DENNIS COLLANTES");
	CfgCredits("Cutscene Animation", "LUI FRANSISCO");
	CfgCredits("Cutscene Animation", "ROB ELSWORTHY");
	CfgCredits("QA Manager", "ARTHUR CHIANG");
	CfgCredits("QA", "BRANNEK GAUDET");
	CfgCredits("QA", "CHRIS CONWAY");
	CfgCredits("QA", "KELLY GRIMES");
	CfgCredits("QA", "NORM 'TUBBZ' BROWN");
	CfgCredits("Technical Assistant", "JAY PENNEY");
	CfgCredits("Office Administrator", "DEIDRE MORGAN");
	CfgCredits("Administration Support", "MELISSA BONE");
	CfgCredits("IT Manager", "MARK HALATA");
	CfgCredits("ROCKSTAR NEW YORK", IDT_Nil);
	CfgCredits("Executive Producer", "SAM HOUSER");
	CfgCredits("Producer", "JERONIMO BARRERA");
	CfgCredits("VP of Creative", "DAN HOUSER");
	CfgCredits("VP of Development", "JAMIE KING");
	CfgCredits("Art Director", "ALEX HORTON");
	CfgCredits("Associate Producer", "NEIL MCCAFFREY");
	CfgCredits("Chief Technology Officer", "GARY J. FOREMAN");
	CfgCredits("Director of Quality Assurance", "JEFF ROSA");
	CfgCredits("Lead Analyst", "BRIAN PLANER");
	CfgCredits("Rockstar Test Team", "CHRISTOPHER PLUMMER");
	CfgCredits("Rockstar Test Team", "CRYSTAL BAHMAIE");
	CfgCredits("Rockstar Test Team", "DEVIN SMITHER");
	CfgCredits("Rockstar Test Team", "JAMES DIMA");
	CfgCredits("Rockstar Test Team", "JAY CAPOZELLO");
	CfgCredits("Rockstar Test Team", "JONATHAN FARBOWITZ");
	CfgCredits("Rockstar Test Team", "LANCE WILLIAMS");
	CfgCredits("Rockstar Test Team", "MICHAEL FLEIZACH");
	CfgCredits("Rockstar Test Team", "SEAN FLAHERTY");
	CfgCredits("Technical Manager", "SANDEEP BISLA");
	CfgCredits("Technical Manager", "DYLAN BROMLEY");
	CfgCredits("Audio and Cutscene Direction by", "NAVID KHONSARI");
	CfgCredits("Voice Over Production by", "JOHN ZURHELLEN");
	CfgCredits("Script Supervision by", "FRANCESKA CLEMENS");
	CfgCredits("Script Supervision by", "KERRY SHAW");
	CfgCredits("Cutscene Supervising Sound Editor", "NICHOLAS MONTGOMERY");
	CfgCredits("Motion Graphics", "MARYAM PARWANA");
	CfgCredits("Research and Analysis", "JON GALLOWAY");
	CfgCredits("Research and Analysis", "GREGORY JOHNSON");
	CfgCredits("Research and Analysis", "JOE HOWELL");
	CfgCredits("Business Development Manager", "SEAN MACALUSO");
	CfgCredits("Production Team", "ELI WEISSMAN");
	CfgCredits("Production Team", "PETER ADLER");
	CfgCredits("Production Team", "PHIL POLI");
	CfgCredits("Production Team", "ANTHONY CARVALHO");
	CfgCredits("Production Team", "JAESUN CELEBRE");
	CfgCredits("Production Team", "TERRY DONOVAN");
	CfgCredits("Production Team", "JENEFER GROSS");
	CfgCredits("Production Team", "JENNIFER KOLBE");
	CfgCredits("Production Team", "ADAM TEDMAN");
	CfgCredits("Production Team", "LAURA PATERSON");
	CfgCredits("Production Team", "PAUL YEATES");
	CfgCredits("Production Team", "HOSI SIMON");
	CfgCredits("Production Team", "BILL WOODS");
	CfgCredits("Production Team", "DAVE KIM");
	CfgCredits("Production Team", "STEVE KNEZEVICH");
	CfgCredits("Production Team", "BRIAN NOTO");
	CfgCredits("Production Team", "DANIEL EINZIG");
	CfgCredits("Production Team", "DEVIN BENNETT");
	CfgCredits("Production Team", "STEPHEN BLISS");
	CfgCredits("Production Team", "LYONEL TOLLEMACHE");
	CfgCredits("Production Team", "JORDAN CHEW");
	CfgCredits("Production Team", "ANDREA BORZUKU");
	CfgCredits("Production Team", "IVAN PAVLOVICH");
	CfgCredits("Production Team", "TIM SWEENEY");
	CfgCredits("Production Team", "STANTON SARJEANT");
	CfgCredits("Production Team", "MICHAEL CALA");
	CfgCredits("Production Team", "JERRY LUNA");
	CfgCredits("Production Team", "ALICE CHUANG");
	CfgCredits("Production Team", "FUTABA HAYASHI");
	CfgCredits("Production Team", "JOHN SCHUHMANN");
	CfgCredits("Production Team", "MIKE TOROK");
	CfgCredits("Production Team", "MAYUMI KOBAYASHI");
	CfgCredits("Production Team", "ELIZABETH SATTERWHITE");
	CfgCredits("Production Team", "NICK GIOVANNETTI");
	CfgCredits("Production Team", "RYAN RAYHILL");
	CfgCredits("Production Team", "TODD ZUNIGA");
	CfgCredits("Production Team", "THOMAS O'DONNELL");
	CfgCredits("Production Team", "MARIA TABIA");
	CfgCredits("Production Team", "MEGAN HENRETTA");
	CfgCredits("Production Team", "JOHN NOTARFRANCESCO");
	CfgCredits("Production Team", "ANGUS WONG");
	CfgCredits("Production Team", "KRISTINE SEVERSON");
	CfgCredits("Production Team", "ROBERT KAROL");
	CfgCredits("ROCKSTAR LONDON", IDT_Nil);
	CfgCredits("LUCIEN KING", IDT_Nil);
	CfgCredits("CHRIS MADGWICK", IDT_Nil);
	CfgCredits("CHRIS WOOD", IDT_Nil);
	CfgCredits("DAIMION PINNOCK", IDT_Nil);
	CfgCredits("DAVID MCCARTHY", IDT_Nil);
	CfgCredits("GRAHAM AINSLEY", IDT_Nil);
	CfgCredits("J�RGEN MOL", IDT_Nil);
	CfgCredits("LAURA BATTISTUZZI", IDT_Nil);
	CfgCredits("MAIKE K�HLER", IDT_Nil);
	CfgCredits("SHINO HORI", IDT_Nil);
	CfgCredits("ROCKSTAR LINCOLN", IDT_Nil);
	CfgCredits("MARK LLOYD", IDT_Nil);
	CfgCredits("TIM BATES", IDT_Nil);
	CfgCredits("CHARLIE KINLOCH", IDT_Nil);
	CfgCredits("ANDY MASON", IDT_Nil);
	CfgCredits("PHIL ALEXANDER", IDT_Nil);
	CfgCredits("DAVE LAWRENCE", IDT_Nil);
	CfgCredits("JASON TRINDALL", IDT_Nil);
	CfgCredits("PHIL DEANE", IDT_Nil);
	CfgCredits("DAVE FAHY", IDT_Nil);
	CfgCredits("STEVE BELL", IDT_Nil);
	CfgCredits("ANDY WEBSTER", IDT_Nil);
	CfgCredits("CHRIS WELSH", IDT_Nil);
	CfgCredits("CAROLA BERENS", IDT_Nil);
	CfgCredits("ANTOINE CABROL", IDT_Nil);
	CfgCredits("FRAN�OIS FOUCHET", IDT_Nil);
	CfgCredits("GABRIEL BIENZOBAS MAURAZA", IDT_Nil);
	CfgCredits("DOMINIC GARCIA", IDT_Nil);
	CfgCredits("ALBERTO TRENTANNI", IDT_Nil);
	CfgCredits("VIACOM CONSUMER PRODUCTS", IDT_Nil);
	CfgCredits("VP, Interactive", "SANDI ISAACS");
	CfgCredits("Sr. Director, Interactive", "HARRY LANG");
	CfgCredits("Manager, Interactive", "DAN FELTS");
	CfgCredits("Coordinator, Interactive", "BETH GILES");
	CfgCredits("SCORE BY NEVERODDOREVEN", IDT_Nil);
	CfgCredits("Composer/Keyboards", "STEVE DONOHOE");
	CfgCredits("Guitar", "RUSSELL SIMPSON");
	CfgCredits("Bass", "JEFF SCALE");
	CfgCredits("Drums", "BRIAN VELLA");
	CfgCredits("VOICEOVER TALENT", IDT_Nil);
	CfgCredits("THE WARRIORS", IDT_Nil);
	CfgCredits("Ajax", "JAMES REMAR");
	CfgCredits("Ash", "EPHRAIM BENTON");
	CfgCredits("Cleon", "DORSEY WRIGHT");
	CfgCredits("Cochise", "DAVID HARRIS");
	CfgCredits("Cowboy", "KURT BAUCCIO");
	CfgCredits("Fox", "TOM WAITES");
	CfgCredits("Rembrandt", "ANDY SENOR");
	CfgCredits("Snow", "SEKOU CAMPBELL");
	CfgCredits("Swan", "MICHAEL BECK");
	CfgCredits("Vermin", "JOE LOTRUGLIO");
	CfgCredits("THE ARMIES OF THE NIGHT", IDT_Nil);
	CfgCredits("Beansie", "OMAR SCROGGINS");
	CfgCredits("Big Moe", "BILLY GRIFFITH");
	CfgCredits("Birdie", "JOE LOTRUGLIO");
	CfgCredits("Chatterbox", "JORDAN GELBER");
	CfgCredits("Crackerjack", "ADAM SEITZ");
	CfgCredits("Cyrus", "MICHAEL POTTS");
	CfgCredits("Diego", "LLOYD FLOYD");
	CfgCredits("Edge", "EL-P");
	CfgCredits("Garrison", "STEVE HAMM");
	CfgCredits("Harrison", "JOHN TORMEY");
	CfgCredits("Jesse", "NELSON VASQUEZ");
	CfgCredits("Knox", "LEE ROSEN");
	CfgCredits("LC", "LEIF RIDDELL");
	CfgCredits("Lemmy", "CHANDLER PARKER");
	CfgCredits("Luther", "OLIVER WYMAN");
	CfgCredits("Masai", "CHARLES PARNELL");
	CfgCredits("Mercy", "DEBORAH VAN VALKENBURGH");
	CfgCredits("Sanchez", "LUIS LOPEZ");
	CfgCredits("Scopes", "DMC");
	CfgCredits("Spider", "MICHAEL GOZ");
	CfgCredits("Starr", "MAINE ANDERS");
	CfgCredits("Sully", "ROB CIHRA");
	CfgCredits("Undercover Cop", "ORFEH");
	CfgCredits("Vargas", "GREG WILSON");
	CfgCredits("Virgil", "CURTISS COOK");
	CfgCredits("Additional Soldiers", "ADAM SCARIMBOLO");
	CfgCredits("Additional Soldiers", "AESOP ROCK");
	CfgCredits("Additional Soldiers", "ALEC TASOOJI");
	CfgCredits("Additional Soldiers", "ANDREW LEE");
	CfgCredits("Additional Soldiers", "ANTHONY CARVALHO");
	CfgCredits("Additional Soldiers", "ANTHONY MACBAIN");
	CfgCredits("Additional Soldiers", "AVIVA YAEL");
	CfgCredits("Additional Soldiers", "BERNARDO DEPAULA");
	CfgCredits("Additional Soldiers", "BERTO COLON");
	CfgCredits("Additional Soldiers", "BETH LYONS");
	CfgCredits("Additional Soldiers", "BURCH WANG");
	CfgCredits("Additional Soldiers", "CAMILLE GASTON");
	CfgCredits("Additional Soldiers", "CESAR DE LEON");
	CfgCredits("Additional Soldiers", "CHRIS 'MUMS' GRANT");
	CfgCredits("Additional Soldiers", "CLEM CHEUNG");
	CfgCredits("Additional Soldiers", "COLIN MORRIS");
	CfgCredits("Additional Soldiers", "DATWON THOMAS");
	CfgCredits("Additional Soldiers", "DAVID JUNG");
	CfgCredits("Additional Soldiers", "DENNIS WHITE");
	CfgCredits("Additional Soldiers", "DIMITRY MICHANN");
	CfgCredits("Additional Soldiers", "DIQEENA MOORE");
	CfgCredits("Additional Soldiers", "DUANE MCLAUGHLIN");
	CfgCredits("Additional Soldiers", "ELI WEISSMAN");
	CfgCredits("Additional Soldiers", "EVAN NEUMANN");
	CfgCredits("Additional Soldiers", "EVAN SEINFELD");
	CfgCredits("Additional Soldiers", "FLACO NAVAJA");
	CfgCredits("Additional Soldiers", "FRANCESKA CLEMENS");
	CfgCredits("Additional Soldiers", "FRED BERMAN");
	CfgCredits("Additional Soldiers", "GEOFFREY AREND");
	CfgCredits("Additional Soldiers", "GREGORY JOHNSON");
	CfgCredits("Additional Soldiers", "HOLTER GRAHAM");
	CfgCredits("Additional Soldiers", "IRINA LAZAR");
	CfgCredits("Additional Soldiers", "JACKSON LOO");
	CfgCredits("Additional Soldiers", "JAMES LORENZO");
	CfgCredits("Additional Soldiers", "JAMIE HECTOR");
	CfgCredits("Additional Soldiers", "JD WILLIAMS");
	CfgCredits("Additional Soldiers", "JEFF GURNER");
	CfgCredits("Additional Soldiers", "JEFFREY HAWKINS");
	CfgCredits("Additional Soldiers", "JEREMY PARISE");
	CfgCredits("Additional Soldiers", "JOHN POGASH");
	CfgCredits("Additional Soldiers", "JOHN SMOOTH");
	CfgCredits("Additional Soldiers", "JOHN ZURHELLEN");
	CfgCredits("Additional Soldiers", "JON BUDINOFF");
	CfgCredits("Additional Soldiers", "KEVIN LYNCH");
	CfgCredits("Additional Soldiers", "KHALIPA OLDJOHN");
	CfgCredits("Additional Soldiers", "LARRY BALLARD");
	CfgCredits("Additional Soldiers", "LEMON");
	CfgCredits("Additional Soldiers", "LLOYD FLOYD");
	CfgCredits("Additional Soldiers", "MR. CEE");
	CfgCredits("Additional Soldiers", "NAVID KHONSARI");
	CfgCredits("Additional Soldiers", "NELSON LEE");
	CfgCredits("Additional Soldiers", "NICHOLAS MONTGOMERY");
	CfgCredits("Additional Soldiers", "PAUL SADO");
	CfgCredits("Additional Soldiers", "POISON PEN");
	CfgCredits("Additional Soldiers", "RANDALL RODRIGUEZ");
	CfgCredits("Additional Soldiers", "RICHARD CHANG");
	CfgCredits("Additional Soldiers", "ROB KAROL");
	CfgCredits("Additional Soldiers", "ROCCO ROSARIO");
	CfgCredits("Additional Soldiers", "RODNEY GARDINER");
	CfgCredits("Additional Soldiers", "RODRICK COVINGTON");
	CfgCredits("Additional Soldiers", "RUBEN LUQUE");
	CfgCredits("Additional Soldiers", "SAM GATES");
	CfgCredits("Additional Soldiers", "STANTON SARJEANT");
	CfgCredits("Additional Soldiers", "VINCENT PARKER");
	CfgCredits("Additional Soldiers", "WILL MCCALL");
	CfgCredits("PEOPLE OF NEW YORK", IDT_Nil);
	CfgCredits("Charlie", "KURT RHODES");
	CfgCredits("Skinny Pete", "KARL WEIBEL");
	CfgCredits("Stefano", "ROCCO SISTO");
	CfgCredits("The DJ", "PAT FLOYD");
	CfgCredits("Twiggy", "JACK LUCENO");
	CfgCredits("Additional Civilians", "ABE AHMED");
	CfgCredits("Additional Civilians", "ALEXANDRA ORTIZ");
	CfgCredits("Additional Civilians", "ANDREW LEE");
	CfgCredits("Additional Civilians", "ARMANDO RIESCO");
	CfgCredits("Additional Civilians", "BEN WEAVER");
	CfgCredits("Additional Civilians", "CHRIS TARDIO");
	CfgCredits("Additional Civilians", "DAVE ISAACS");
	CfgCredits("Additional Civilians", "DAVID LASSITER");
	CfgCredits("Additional Civilians", "DAVID SHIH");
	CfgCredits("Additional Civilians", "DAVID WHITE");
	CfgCredits("Additional Civilians", "DENNIS OSTERMEIER");
	CfgCredits("Additional Civilians", "DIDI WONG");
	CfgCredits("Additional Civilians", "FIONA GALLAGHER");
	CfgCredits("Additional Civilians", "GREGORY JOHNSON");
	CfgCredits("Additional Civilians", "HANA MOON");
	CfgCredits("Additional Civilians", "HETIENNE PARK");
	CfgCredits("Additional Civilians", "JESSE PEREZ");
	CfgCredits("Additional Civilians", "J-HOOD");
	CfgCredits("Additional Civilians", "JOEL DE LA FUENTE");
	CfgCredits("Additional Civilians", "JORDIN RUDERMAN");
	CfgCredits("Additional Civilians", "KEITH JAMAL DOWNING");
	CfgCredits("Additional Civilians", "KENYAN LEWIS PARIS");
	CfgCredits("Additional Civilians", "KEVIN MERRILL WILSON");
	CfgCredits("Additional Civilians", "KIM MARIE LYNCH");
	CfgCredits("Additional Civilians", "LANE KEOUGH");
	CfgCredits("Additional Civilians", "LOUIS TORELLAS");
	CfgCredits("Additional Civilians", "MESSERET STROMAN");
	CfgCredits("Additional Civilians", "MIKE ZOCCANO");
	CfgCredits("Additional Civilians", "NATALIE BELCON");
	CfgCredits("Additional Civilians", "NATALYA WILSON");
	CfgCredits("Additional Civilians", "NICK MONTGOMERY");
	CfgCredits("Additional Civilians", "PETER APPEL");
	CfgCredits("Additional Civilians", "ROY WOO");
	CfgCredits("Additional Civilians", "SUE JEAN KIM");
	CfgCredits("Additional Civilians", "SY BARSTES");
	CfgCredits("Additional Civilians", "TARA RADCLIFFE");
	CfgCredits("Additional Civilians", "TOM VERGOW");
	CfgCredits("Additional Civilians", "VALENCIA YEARWOOD");
	CfgCredits("Additional Civilians", "VANESE SMITH");
	CfgCredits("Additional Civilians", "YVETTE EDERY");
	CfgCredits("THE POLICE", IDT_Nil);
	CfgCredits("ANTHONY MANGANO", IDT_Nil);
	CfgCredits("CHAD COLEMAN", IDT_Nil);
	CfgCredits("DAVID BROWN", IDT_Nil);
	CfgCredits("JAMES BIBERI", IDT_Nil);
	CfgCredits("KAPER", IDT_Nil);
	CfgCredits("KEITH MURPHY", IDT_Nil);
	CfgCredits("LARRY FLEISCHMAN", IDT_Nil);
	CfgCredits("MATT MCCARTHY", IDT_Nil);
	CfgCredits("MIKE ARKIN", IDT_Nil);
	CfgCredits("ROBERT LARKIN", IDT_Nil);
	CfgCredits("SETH ABRAMS", IDT_Nil);
	CfgCredits("TOM ZURHELLEN", IDT_Nil);
	CfgCredits("TRON", IDT_Nil);
	CfgCredits("THE DEALERS", IDT_Nil);
	CfgCredits("ANDREW TOTOLOS", IDT_Nil);
	CfgCredits("CHRIS VERNON", IDT_Nil);
	CfgCredits("DAN MASTROGIORGIO", IDT_Nil);
	CfgCredits("JESSE LENAT", IDT_Nil);
	CfgCredits("JUBAR CROSWELL", IDT_Nil);
	CfgCredits("LANCE WILLIAMS", IDT_Nil);
	CfgCredits("LOU CARBONNEAU", IDT_Nil);
	CfgCredits("MATTHEW POZZI", IDT_Nil);
	CfgCredits("OLIVER VAQUER", IDT_Nil);
	CfgCredits("RON SIMONS", IDT_Nil);
	CfgCredits("SCOTT KELLY", IDT_Nil);
	CfgCredits("SEAN EDEN", IDT_Nil);
	CfgCredits("SHAWN ANDREW", IDT_Nil);
	CfgCredits("SHEEK", IDT_Nil);
	CfgCredits("STYLES P", IDT_Nil);
	CfgCredits("TARIK LOWE", IDT_Nil);
	CfgCredits("TY JONES", IDT_Nil);
	CfgCredits("WILHELM LEWIS", IDT_Nil);
	CfgCredits("THE HOBOS", IDT_Nil);
	CfgCredits("DANIEL VAN ZANT", IDT_Nil);
	CfgCredits("JOE HOLT", IDT_Nil);
	CfgCredits("JOHN ZURHELLEN", IDT_Nil);
	CfgCredits("KEVIN FREITAS", IDT_Nil);
	CfgCredits("ROB NELSON", IDT_Nil);
	CfgCredits("ROBERT JASON JACKSON", IDT_Nil);
	CfgCredits("WILLY CARPENTER", IDT_Nil);
	CfgCredits("MOTION CAPTURE PERFORMERS", IDT_Nil);
	CfgCredits("BERNARDO DEPAULA", IDT_Nil);
	CfgCredits("CHANDLER PARKER", IDT_Nil);
	CfgCredits("CHRIS TARDIO", IDT_Nil);
	CfgCredits("DANIEL HALL", IDT_Nil);
	CfgCredits("EPHRAIM BENTON", IDT_Nil);
	CfgCredits("JAMA WILLIAMSON", IDT_Nil);
	CfgCredits("JEFF WARD", IDT_Nil);
	CfgCredits("JEFFREY HAWKINS", IDT_Nil);
	CfgCredits("JOE LOTRUGLIO", IDT_Nil);
	CfgCredits("KIKI GOINS", IDT_Nil);
	CfgCredits("KURT BAUCCIO", IDT_Nil);
	CfgCredits("LARRY BALLARD", IDT_Nil);
	CfgCredits("MANNY SIVERIO", IDT_Nil);
	CfgCredits("MARY STIEFVATER", IDT_Nil);
	CfgCredits("ROBERT JASON JACKSON", IDT_Nil);
	CfgCredits("RODRICK COVINGTON", IDT_Nil);
	CfgCredits("TARA RADCLIFFE", IDT_Nil);
	CfgCredits("VANEIK ECHEVERRIA", IDT_Nil);
	CfgCredits("WILHELM LEWIS", IDT_Nil);
	CfgCredits("WILL MCCALL", IDT_Nil);
	CfgCredits(""".."THEME FROM 'THE WARRIORS'"..""", IDT_Nil);
	CfgCredits("Barry de Vorzon", IDT_Nil);
	CfgCredits("Written by B. de Vorzon", IDT_Nil);
	CfgCredits("Published by Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."NOWHERE TO RUN"..""", IDT_Nil);
	CfgCredits("Arnold McCuller", IDT_Nil);
	CfgCredits("Written by Holland, Dozier, Holland", IDT_Nil);
	CfgCredits("Published by EMI Music Publishing", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."ECHOES IN MY MIND"..""", IDT_Nil);
	CfgCredits("Mandrill", IDT_Nil);
	CfgCredits("Written by C. Wilson, L. Wilson, C.", IDT_Nil);
	CfgCredits("Cavell, Dr. R. Wilson, W. Wilson", IDT_Nil);
	CfgCredits("Published by Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."THE FIGHT"..""", IDT_Nil);
	CfgCredits("Barry de Vorzon", IDT_Nil);
	CfgCredits("Written by B. de Vorzon", IDT_Nil);
	CfgCredits("Published by Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."IN THE CITY"..""", IDT_Nil);
	CfgCredits("Joe Walsh", IDT_Nil);
	CfgCredits("Written by B. de Vorzon, J. Walsh", IDT_Nil);
	CfgCredits("Published by Wow & Flutter Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."LOVE IS A FIRE"..""", IDT_Nil);
	CfgCredits("Genya Ravan", IDT_Nil);
	CfgCredits("Written by J. Vastano, V. Poncia", IDT_Nil);
	CfgCredits("Published by EMI Music Publishing/", IDT_Nil);
	CfgCredits("Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."BASEBALL FURIES CHASE"..""", IDT_Nil);
	CfgCredits("Barry de Vorzon", IDT_Nil);
	CfgCredits("Written by B. de Vorzon", IDT_Nil);
	CfgCredits("Published by Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."YOU'RE MOVIN' TOO SLOW"..""", IDT_Nil);
	CfgCredits("Johnny Vastano", IDT_Nil);
	CfgCredits("Written by E. Mercury, W. Smith", IDT_Nil);
	CfgCredits("Published by Salamani Music/", IDT_Nil);
	CfgCredits("Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."LAST OF AN ANCIENT BREED"..""", IDT_Nil);
	CfgCredits("Desmond Child", IDT_Nil);
	CfgCredits("Written by D. Child", IDT_Nil);
	CfgCredits("Published by Famous Music", IDT_Nil);
	CfgCredits("(p) 1974 A&M Records", IDT_Nil);
	CfgCredits("Courtesy of Universal Music", IDT_Nil);
	CfgCredits(""".."DON'T HOLD BACK"..""", IDT_Nil);
	CfgCredits("Chanson", IDT_Nil);
	CfgCredits("Written by J. Jamerson, Jr., D. Williams", IDT_Nil);
	CfgCredits("Published by Jamerson Music, Inc", IDT_Nil);
	CfgCredits("(p) 1978 Ariola Records", IDT_Nil);
	CfgCredits("Courtesy of Jamerson Music, Inc", IDT_Nil);
	CfgCredits(""".."GET DOWN"..""", IDT_Nil);
	CfgCredits("Gene Chandler", IDT_Nil);
	CfgCredits("Written by James A. Thompson, Jr", IDT_Nil);
	CfgCredits("Published by Cachand Music, Inc", IDT_Nil);
	CfgCredits("(p) 1978 20th Century Records", IDT_Nil);
	CfgCredits("Courtesy of BR Music Two B.V.", IDT_Nil);
	CfgCredits(""".."HERE COMES THAT SOUND AGAIN"..""", IDT_Nil);
	CfgCredits("Love De-Luxe", IDT_Nil);
	CfgCredits("Written by Alan Hawshaw", IDT_Nil);
	CfgCredits("Published by Hawkshaw Music", IDT_Nil);
	CfgCredits("(p) 1979 Warner Bros. Records", IDT_Nil);
	CfgCredits("Courtesy of Warner Music Interactive", IDT_Nil);
	CfgCredits("UK and Hawkshaw Music", IDT_Nil);
	CfgCredits(""".."I LOVE LIVIN' IN THE CITY"..""", IDT_Nil);
	CfgCredits("Fear", IDT_Nil);
	CfgCredits("Written by Lee Ving", IDT_Nil);
	CfgCredits("Published by Toxic Tunes/Range", IDT_Nil);
	CfgCredits("War Music", IDT_Nil);
	CfgCredits("(p) 1978 Slash Records", IDT_Nil);
	CfgCredits("Courtesy of London-Sire Records Ltd", IDT_Nil);
	CfgCredits("by arrangement with Warner Strategic", IDT_Nil);
	CfgCredits("Marketing", IDT_Nil);
	CfgCredits(""".."KNOCK ON WOOD"..""", IDT_Nil);
	CfgCredits("Amii Stewart", IDT_Nil);
	CfgCredits("Written by E. Floyd, S. Cropper", IDT_Nil);
	CfgCredits("Published by Universal Music", IDT_Nil);
	CfgCredits("(p) 1978 Hansa Productions Ltd", IDT_Nil);
	CfgCredits("Courtesy of Sanctuary Records Group", IDT_Nil);
	CfgCredits(""".."PUEBLO LATINO"..""", IDT_Nil);
	CfgCredits("Spanish Harlem Orchestra", IDT_Nil);
	CfgCredits("Written by C. Curet Alonso", IDT_Nil);
	CfgCredits("Published by FAF Publishing", IDT_Nil);
	CfgCredits("(p) 2002 Rope-A-Dope Records", IDT_Nil);
	CfgCredits("Courtesy of Artemis Records", IDT_Nil);
	CfgCredits(""".."REMEMBER"..""", IDT_Nil);
	CfgCredits("Vivien Vee", IDT_Nil);
	CfgCredits("Written by C. Simonetti, G. Meo", IDT_Nil);
	CfgCredits("Published by Market Srl", IDT_Nil);
	CfgCredits("(p) 1979 Banana Records", IDT_Nil);
	CfgCredits("Courtesy of Market Srl", IDT_Nil);
	CfgCredits(""".."TRAIGO DE TODO"..""", IDT_Nil);
	CfgCredits("Alberto Alberto", IDT_Nil);
	CfgCredits("Published by Alberto Alberto", IDT_Nil);
	CfgCredits("(p) 2005 Alberto Alberto", IDT_Nil);
	CfgCredits("Courtesy of Patricio and Brenda Lahman", IDT_Nil);
	CfgCredits(""".."WHEN YOU'RE IN LOVE WITH A BEAUTIFUL WOMAN"..""", IDT_Nil);
	CfgCredits("Dr. Hook", IDT_Nil);
	CfgCredits("Written by Even Stevens", IDT_Nil);
	CfgCredits("Published by EMI Music Publishing", IDT_Nil);
	CfgCredits("(p) 1978 Capitol Records", IDT_Nil);
	CfgCredits("Courtesy of EMI Music", IDT_Nil);
	CfgCredits(""".."SHAKE IT"..""", IDT_Nil);
	CfgCredits("Ian Matthews", IDT_Nil);
	CfgCredits("Written by Terence Boylan", IDT_Nil);
	CfgCredits("Published by Steamed Clam Music", IDT_Nil);
	CfgCredits("(p) 1978 Rockburgh Records, 2005 Ian Matthews", IDT_Nil);
	CfgCredits("Courtesy of Ian Matthews", IDT_Nil);
	CfgCredits(""".."BLOOD STAINS"..""", IDT_Nil);
	CfgCredits("The Angry Cocks", IDT_Nil);
	CfgCredits("Written by Wheels, Knuckles, and Birdie", IDT_Nil);
	CfgCredits(""".."SHIT BLISTERS, SALINE BALLS"..""", IDT_Nil);
	CfgCredits("The Angry Cocks", IDT_Nil);
	CfgCredits("Written by Wheels, Knuckles, and Birdie", IDT_Nil);
	CfgCredits(""".."NUT ROLLER"..""", IDT_Nil);
	CfgCredits("The Angry Cocks", IDT_Nil);
	CfgCredits("Written by Wheels, Knuckles, and Birdie", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("The trademarks associated with CBGB's are used under license", IDT_Nil);
	CfgCredits("from [ CBGB's ] to Rockstar Games, Inc.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("The trademarks and copyright associated with", IDT_Nil);
	CfgCredits("the NYC Subway Map are used under license", IDT_Nil);
	CfgCredits("from [ Michael Calgano] to Rockstar Games, Inc.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("NEW YORK POST is a registered trademark of NYP Holdings, Inc.", IDT_Nil);
	CfgCredits("and is used with permission.  All Rights reserved.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("The 'adidas' word mark, the Three-Stripes trademark and the", IDT_Nil);
	CfgCredits("Trefoil Logo are the property of Adidas-Salomon AG.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("CHAMPION and the Bow Tie logo used under license from", IDT_Nil);
	CfgCredits("Federal-Mogul Ignition Company, a wholly-owned subsidiary", IDT_Nil);
	CfgCredits("of Federal-Mogul Corporation.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("This game is not endorsed by, or have any affiliation with the", IDT_Nil);
	CfgCredits("Metropolitan Transportation Authority or the", IDT_Nil);
	CfgCredits("New York City Transit Authority.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("All other marks and trademarks are properties of their respective owners.", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("A SPECIAL THANKS", IDT_Nil);
	CfgCredits("Rita Liberator", IDT_Nil);
	CfgCredits("Liezl Jacinto", IDT_Nil);
	CfgCredits("Stefano Zanger", IDT_Nil);
	CfgCredits("Dick Zigun", IDT_Nil);
	CfgCredits("Davif Gratt", IDT_Nil);
	CfgCredits("Liad Krispin", IDT_Nil);
	CfgCredits("Abby Guyer", IDT_Nil);
	CfgCredits("Russ Karablim", IDT_Nil);
	CfgCredits("Arthur Warren", IDT_Nil);
	CfgCredits("David Lerner Esq.", IDT_Nil);
	CfgCredits("Deno's Wonder Wheel Coney Island, New York", IDT_Nil);
	CfgCredits("The New York Post", IDT_Nil);
	CfgCredits("Michael Calcagno", IDT_Nil);
	CfgCredits("OP", IDT_Nil);
	CfgCredits("The Village Voice", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("", IDT_Nil);
	CfgCredits("SPECIAL THANKS TO SSUR FOR COMMISSIONING", IDT_Nil);
	CfgCredits("THE FOLLOWING NYC GRAFFITI ARTISTS:", IDT_Nil);
	CfgCredits("Futura", IDT_Nil);
	CfgCredits("Dondi", IDT_Nil);
	CfgCredits("Naco", IDT_Nil);
	CfgCredits("Tracy 168", IDT_Nil);
	CfgCredits("Revolt", IDT_Nil);
	CfgCredits("Jamestop / Jee2 / Afroman", IDT_Nil);
	CfgCredits("Duro", IDT_Nil);
	CfgCredits("Kano", IDT_Nil);
	CfgCredits("Iz the Wiz", IDT_Nil);
	CfgCredits("Stay High 149", IDT_Nil);
	CfgCredits("Crime / Crimewave / Crimemala", IDT_Nil);
	CfgCredits("Hurst", IDT_Nil);
	CfgCredits("ElHadj", IDT_Nil);
	CfgCredits("Flint 707", IDT_Nil);
	CfgCredits("Seen", IDT_Nil);
	CfgCredits("Cap / Cap One", IDT_Nil);
	CfgCredits("Cey (Cey Adams)", IDT_Nil);
	CfgCreditsData=IDT_Nil;
end

CfgCreditsData();